apiVersion: v1
kind: Service
metadata:
    name: "myazurekuberneties-ee96"
    labels:
        app: "myazurekuberneties-ee96"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myazurekuberneties-ee96"